name: Terraform Validate

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Terraform module
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform validate -no-color
